#!/bin/bash

apt-get update
apt-get -y dist-upgrade

rm /etc/localtime
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

apt-get -y install ntp

## reconfigure ntp server
grep -v ^server /etc/ntp.conf > /etc/ntp.conf.gs
echo server metadata.google.internal iburst>> /etc/ntp.conf.gs
mv /etc/ntp.conf.gs /etc/ntp.conf
service ntp restart

## redirect console output to ttyS0 for gcutil getserialportoutput
sed -i -e 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="console=ttyS0,38400n8"/' /etc/default/grub
update-grub

## disable ipv6 - not supported in GCE
cat > /etc/sysctl.d/70-disable-ipv6.conf<<EOF
net.ipv6.conf.all.disable_ipv6 = 1
EOF

## generated by /usr/share/google/set-hostname
rm /etc/hostname

## reset hosts
cat > /etc/hosts<<EOF
127.0.0.1 localhost
169.254.169.254 metadata.google.internal metadata
EOF

## versions prior to 1.0.4 cause performance issues
apt-get -y remove irqbalance

cat >/etc/ssh/sshd_not_to_be_run<<EOF
GOOGLE
EOF

# Basic sshd config, as per GCE image guide
cat > /etc/ssh/sshd_config<<EOF
PasswordAuthentication no

PermitRootLogin no
PermitTunnel no
AllowTcpForwarding yes
X11Forwarding no

ClientAliveInterval 420

UseDNS no
GSSAPIAuthentication no
EOF

rm /etc/ssh/ssh_host_key
rm /etc/ssh/ssh_host_rsa_key*
rm /etc/ssh/ssh_host_dsa_key*
rm /etc/ssh/ssh_host_ecdsa_key*

usermod -L root

